# -*- mode: ruby -*-


Vagrant.configure(2) do |config|
  config.hostmanager.enable = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "puppet" do |puppet|
    # puppetmaster on centos/7
    puppet.vm.box = "centos/7" # name of the box on vagrant website.
    puppet.vm.hostname = "puppetmaster.omps.in"
    puppet.vm.network :private_network, ip: "10.0.0.10"
    puppet.hostmanager.alias = %w(puppet)
  end

  # config.vm.define "agent1" do |agent1|
  #   # agent1 on centos/7
  #   agent1.vm.box = "centos/7"
  # agent1.vm.hostname = "agent1.omps.in"
  # agent1.vm.network :private_network, ip: "10.0.0.11"
  # agent1.hostmanager.alias = %w(agent1)
  # end


  config.vm.define "agent2" do |agent2|
    #agent2 on debian/ubuntu
    agent2.vm.box = "ubuntu/trusty64"
    agent2.vm.hostname = "agent2.omps.in"
    agent2.vm.network :private_network, ip: "10.0.0.12"
    agent2.hostmanager.alias = %w(agent2)
  end
end
